# define the `Secret` to define the necessary environment variables for the mongo server and mongo-express.
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: Z2FuZ29mZm91cg==
  mongo-root-password: YWxsZnJpZW5kcw==
